### ISSUE TITLE
大佬，我一次只能下载50个，我们知识库里有300个，能不能把上限改为用户自定义呀

### ISSUE THREAD

**Issue by Emdoor-MoChen** [Microanswer/ding-doc-downloader#1]
大佬，我一次只能下载50个，我们知识库里有300个，能不能把上限改为用户自定义呀

**Comment by Microanswer** [comment]
嗯？还有这种事？我没限制个数呀，　有截图没，我瞧瞧

**Comment by Emdoor-MoChen** [comment]
![1c5818dc443984852ead4ee3d5b48c6](https://github.com/user-attachments/assets/74badd11-2373-44bb-bdf4-a9f148e8f6a0)

**Comment by Microanswer** [comment]
噢，我知道了，应该是那个接口是分页加载，每页５０个文件，我没有继续加载后续的。我今天如果有时间修复一下。

**Comment by Emdoor-MoChen** [comment]
好的好的，感谢您的帮助

**Comment by Microanswer** [comment]
对了，那你能选中的５０个文件里，能够正常下载吗？

**Comment by Emdoor-MoChen** [comment]
可以的，下载后都正常的，我目前是把知识库的文件复制到另一个新建的知识库，然后下载50个，就删除50个，通过刷新网页，循环利用您的插件

**Comment by Microanswer** [comment]
nice。这点小事，举手之劳，不必打赏
